### PR TITLE
Experiments with OpenCL ICD loaders

### PR DESCRIPTION
**Pull request by jaimergp**
Trying to understand the complexities behind OpenCL ICD loaders and how this affects environments with mixed linking strategies.

## Description

__Disclaimer: This might be wrong!__

In contrast with CUDA, where Nvidia governs the full pipeline, when it comes to OpenCL, there are multiple implementations available, provided by different vendors, organizations and projects. These implementations are called ICDs. When it comes to using one (or more) of them in an application, the developer might face the decision of linking against one specific ICD. What if the project wants to support several implementations? Here's where the loader can help: it provides a unified interface to all the possible ICDs present in the system, so the projects can link to the loader and forget about generating all the possible variants.

However, problems might arise if both strategies are used by different pacakges that are loaded in the same process. For example, a Python script is using a packaged linked against the loader, _and_ another package that links against the ICD directly. For this reason, Conda Forge requires to link against the ICD loader so packages within conda-forge are compatible. 

This can cause problems with packages _outside_ conda-forge, though.

## Packages available on conda-forge

Following `conda-forge` recommendations, packages are expected to link to the ICD loader:

* On Linux, the loader is provided by `ocl-icd`. By default, the loader will only see ICDs present in the conda environment. If system's ICDs are needed (e.g. Nvidia's), you can also install `ocl-icd-system` to symlink the system locations and make them visible.
* On MacOS and Windows, the loader is provided by `khronos-opencl-icd-loader`.
* MacOS also provides Apple's own implementation, not natively compatible with the loader mechanism. A wrapper is available to expose it as such: `ocl_icd_wrapper_apple`. This wrapper is not needed for other vendors.

### Scenario A: using the loader

TBD

### Scenario B: linking against Nvidia's OpenCL

TBD

### Scenario C: linking against Apple's OpenCL (MacOS only)

TBD

### CODE REVIEW

**Comment by peastman** [comment]
I'm not sure that I completely understand all the changes, so let me try to summarize and you can correct me if I misunderstood some of it.

You added an `opencl_impl` option to select what OpenCL implementation it's using.  The meaning of that option varies between platforms.

On Mac, it selects whether to use the implementation built into the OS (which doesn't use the ICD mechanism) or a third party ICD loader.  Since these implementations use different mechanisms, it produces different binaries that work in different ways.  So this should affect all stages: build, test, and run.

On Linux and Windows the situation is a bit different.  All implementations use the ICD mechanism, and all loaders are supposed to be binary compatible with each other.  So if I'm understanding correctly, the option should really only affect the run stage.  We need to get a version of libOpenCL to build against from somewhere, and if we want to test that platform then we need to install an OpenCL implementation from somewhere at test time.  So really this option should only affect the run stage.

Does that sound correct?

**Comment by jaimergp** [comment]
My idea is that `opencl_impl` controls whether we link to the ICD loader or a vendor ICD. If it's set up to link to the ICD loader, we link against the corresponding `conda` package (Linux: `ocl-icd`, Windows: `khronos-icd-loader`, MacOS: `khronos-icd-loader` + the ICD wrapper). Otherwise, we link to the vendor directly (Linux / Windows: Nvidia, MacOS: Apple).

The build / test / run distinctions are only there to control the needed dependencies. If `opencl_impl` selects the ICD loaders, we need to depend on them; otherwise they shouldn't be there.

Everything else you said is correct.

Also, I am not done yet with this prototype - the review requests was sent automatically upon PR creation, sorry about that!

**Comment by peastman** [comment]
On Windows and Linux, it shouldn't make any difference what you link to at build time.  All ICD loaders are supposed to have the same name and be binary compatible with each other.  All that matters is what's in the library path at runtime.

**Comment by peastman** [comment]
I haven't verified that ocl-icd actually follows the spec regarding that though.

**Comment by jaimergp** [comment]
So we only need the `opencl_impl` selector in MacOS?

**Comment by peastman** [comment]
We still need it on other platforms, because it affects what gets listed as runtime dependencies in the recipe.  That is, when someone installs OpenMM, will it also install ocl-icd?

**Comment by jaimergp** [comment]
> We still need it on other platforms, because it affects what gets listed as runtime dependencies in the recipe. That is, when someone installs OpenMM, will it also install ocl-icd?

Yes, in the `opencl_impl == icdloader` variant:

* Linux: `ocl-icd`
* Windows: `khronos-icd-loader`
* MacOS: `khronos-icd-loader` + the ICD wrapper

**Comment by jaimergp** [comment]
Woohoo, we have build artifacts now!

https://dev.azure.com/openmm/feedstock-builds/_build/results?buildId=382&view=artifacts&type=publishedArtifacts

**Comment by jaimergp** [comment]
To try any of the published packages above:

1. Go to the[ artifacts URL for that build](https://dev.azure.com/openmm/feedstock-builds/_build/results?buildId=382&view=artifacts&type=publishedArtifacts)
2. Choose your build (e.g. `linux_opencl_implicdloader` for Linux + OpenCL linked through `ocl-icd`)
3. Download the package to disk by clicking on it (there's no permalink, sorry)
image
4. Create an environment out of the local package and update it without activating it:

```
$> conda create -n openmm-icd-loader ~/Downloads/openmm-7.4.2-py38hc2264bd_icdloader_0.tar.bz2
$> conda update -n openmm-icd-loader --all
```

5. Now, you can activate it and run any tests:

```
$> conda activate openmm-icd-loader
$> python -m simtk.testInstallation

OpenMM Version: 7.4.2
Git Revision: 849e56e5f0a51778e3e7292eb02d2aeb8f721d36

There are 2 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.30255e-06

All differences are within tolerance.

$> conda install pocl
$> python -m simtk.testInstallation

OpenMM Version: 7.4.2
Git Revision: 849e56e5f0a51778e3e7292eb02d2aeb8f721d36

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.30302e-06
Reference vs. OpenCL: 6.74157e-06
CPU vs. OpenCL: 7.30093e-07

All differences are within tolerance.
```

**Comment by jaimergp** [comment]
My local experiments on **Linux** point out that linking to `ocl-icd` or Nvidia's ICD doesn't make a difference, due to [`conda-build` rpath treatment](https://docs.conda.io/projects/conda-build/en/latest/resources/use-shared-libraries.html). 

**Case A**: linking to `ocl-icd`

1. ✔️ `ocl-icd-system` is included too, so system-wide ICDs are linked to the conda env and discoverable. OpenMM sees Nvidia's OpenCL right away. `pocl` is not present yet anyway.
2. ✔️ If I install `pocl`, Nvidia's is still used. No problems here.

**Case B**: linking to Nvidia's ICD

1. ✔️ Nor `ocl-icd` neither `ocl-icd-system` are listed as dependencies. At this point, OpenMM can only see Nvidia's OpenCL (or whatever the system's ICD is).
2. 🛑 Installing `pocl` brings in `ocl-icd`, which is loaded instead (with no errors, thanks to ABI compatibility) due to how rpath is handled (libs in the conda env take precedence). This makes `pocl` the only OpenCL available because `ocl-icd-system` is not installed at this point.
3. ✔️ If I install `ocl-icd-system` so the system locations are visible to `ocl-icd`, then Nvidia's OpenCL is correctly used instead of `pocl`.

***

This all falls within our expectations. The only case we need to control is B2, which doesn't exist under Case A at all.


***

This should reproduce the situations above:

```
#!/bin/bash

# Make sure to download both package variants for your platform and replace the paths below

openmm_ocl_system="~/Downloads/openmm-7.4.2-py38h825ee52_icdsystem_0.tar.bz2"
openmm_ocl_loader="~/Downloads/openmm-7.4.2-py38hc2264bd_icdloader_0.tar.bz2"

## Case A

# Setup
conda create -n openmm_ocl_loader $openmm_ocl_loader
conda update -n openmm_ocl_loader --all
conda activate openmm_ocl_loader

# Situation A1
python -m simtk.testInstallation # should see Nvidia's OpenCL if CUDA is installed

# Situation A2
conda install pocl
python -m simtk.testInstallation # should see Nvidia's OpenCL if CUDA is installed


## Case B
conda create -n openmm_ocl_system $openmm_ocl_system
conda update -n openmm_ocl_system --all
conda activate openmm_ocl_system

# Situation B1
python -m simtk.testInstallation # should see Nvidia's OpenCL if CUDA is installed

# Situation B2 
conda install pocl
python -m simtk.testInstallation # will not see Nvidia's OpenCL!!!!

# Situation B3
conda install ocl-icd-system
python -m simtk.testInstallation # should see Nvidia's OpenCL if CUDA is installed
```

**Comment by jaimergp** [comment]
I have also borrowed this script (attached below) from [`pyopencl` docs](https://documen.tician.de/pyopencl/) to try provide reproducible use cases where two OpenCL implementations might be used in the same process. In this case, we will be trying to force an error using this environment:

* `openmm` linked against Nvidia's ICD
* `ocl-icd` and `ocl-icd-system` installed
* `pocl`, `numpy`, `pyopencl`

These are the results:

```
$>python demo.py

OpenMM Version: 7.4.2
Git Revision: 849e56e5f0a51778e3e7292eb02d2aeb8f721d36

There are 4 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 CUDA - Successfully computed forces
4 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.30653e-06
Reference vs. CUDA: 6.73114e-06
CPU vs. CUDA: 7.85349e-07
Reference vs. OpenCL: 6.75312e-06
CPU vs. OpenCL: 8.17846e-07
CUDA vs. OpenCL: 2.22264e-07

All differences are within tolerance.
Choose platform:
[0] <pyopencl.Platform 'NVIDIA CUDA' at 0x5619db5eca90>
[1] <pyopencl.Platform 'Portable Computing Language' at 0x2b77b9bba008>
Choice [0]:1
Set the environment variable PYOPENCL_CTX='1' to avoid being asked again.
[0. 0. 0. ... 0. 0. 0.]
0.0
```

Note how OpenMM is using Nvidia's OpenCL, and pyopencl is using pocl, in the same process.

Again, all within our expectations. No errors reported since both implementations are loaded through `ocl-icd` even though OpenMM was linked against Nvidia's ICD.

***

`demo.py`:

```python

#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import absolute_import, print_function
import numpy as np
import pyopencl as cl

a_np = np.random.rand(50000).astype(np.float32)
b_np = np.random.rand(50000).astype(np.float32)

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

mf = cl.mem_flags
a_g = cl.Buffer(ctx, mf.READ_ONLY | mf.COPY_HOST_PTR, hostbuf=a_np)
b_g = cl.Buffer(ctx, mf.READ_ONLY | mf.COPY_HOST_PTR, hostbuf=b_np)

prg = cl.Program(ctx, """
__kernel void sum(
    __global const float *a_g, __global const float *b_g, __global float *res_g)
{
  int gid = get_global_id(0);
  res_g[gid] = a_g[gid] + b_g[gid];
}
""").build()

res_g = cl.Buffer(ctx, mf.WRITE_ONLY, a_np.nbytes)
prg.sum(queue, a_np.shape, None, a_g, b_g, res_g)

res_np = np.empty_like(a_np)
cl.enqueue_copy(queue, res_np, res_g)

# Check on CPU with Numpy:
print(res_np - (a_np + b_np))
print(np.linalg.norm(res_np - (a_np + b_np)))
assert np.allclose(res_np, a_np + b_np)
```

**Comment by peastman** [comment]
That's excellent!

**Comment by jchodera** [comment]
Wow, thanks for the excellent testing report, @jaimergp!

**Comment by jaimergp** [comment]
Just ran same tests on __MacOS__.  Analysis following soon.

[tests_osx.zip](https://github.com/openmm/openmm-feedstock/files/4971579/tests_osx.zip)

***

_Disclaimer: I can only run this on a VM with no GPU, so we'll need more tests on a GPU-enabled Mac._

__Case A__: Linked against `khronos-opencl-icd-loader` + `ocl_icd_wrapper_apple`

1. OpenMM sees Apple as the OpenCL provider, but it's rejected because it's not compatible (`OpenCL platform error: No compatible OpenCL platform is available`).
2. After installing `pocl`, it is loaded as the OpenCL implementation and finishes with no warnings.

__Case B__: Linked against Apple's OpenCL directly, no ICD

1. Same as A1.
2. Installing `pocl` brings in `khronos-opencl-icd-loader` too. Same behaviour: `OpenCL platform error: No compatible OpenCL platform is available`. This means that OpenMM is _not_ seeing the ICD loader at all.
3. Adding `ocl_icd_wrapper_apple` does not change the behavior. OpenMM still sees Apple's OpenCL as before.
4. Installing `pyopencl` and running `demo.py` to force an error with both OpenCL implementations loaded at the same time does not cause any errors! OpenMM stills ignores Apple's OpenCL, and PyOpenCL is able to use `pocl` _and_ Apple as OpenCL implementations to compute the example demo. 

So we have learnt one thing: there are no immediate segfaults when both implementations are in memory, but I don't know if we can force that with more extensive testing. 

One question at this point, @peastman, which OpenCL platforms are available on MacOS? Apple's OpenCL on CPU is rejected, but maybe GPU is not? I can't test this :/

**Comment by jaimergp** [comment]
A friend helped test this on a proper Mac with GPU. Results are the same: [osx_gpu.log](https://github.com/openmm/openmm-feedstock/files/4972526/osx_gpu.log). Only difference is that OpenMM now considers Apple's OpenCL as a valid provider so we don't see those errors on A1 and B1. B4 doesn't cause any segfaults here either!

**Comment by peastman** [comment]
That sounds like what we expected.  Apple sort of supports running OpenCL on the CPU, but it's so limited that it's basically useless.  That's why we reject it as incompatible and require a GPU.

**Comment by jaimergp** [comment]
@peastman Could you run [these tests](https://github.com/openmm/openmm-feedstock/pull/1#issuecomment-663482745) on a GPU-equipped Mac? @bdice is reporting segfaults in his CUDA-enabled system (that other Mac I used didn't have CUDA), but it could be unrelated to OpenCL (we are looking into this). In the meantime we can see if it's reproducible on other systems.

**Comment by peastman** [comment]
My Mac has two GPUs, one Intel and one AMD.  CUDA is not installed.  Here's what I get for each of the tests.

A1

```
OpenMM Version: 7.4.2
Git Revision: Unknown

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.29092e-06
Reference vs. OpenCL: 6.76107e-06
CPU vs. OpenCL: 8.68951e-07

All differences are within tolerance.
```

A2

```
OpenMM Version: 7.4.2
Git Revision: Unknown

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
pocl warning: encountered incomplete implementation in /Users/runner/miniforge3/conda-bld/pocl_1594943201280/work/lib/CL/clGetDeviceInfo.c:119
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.29894e-06
Reference vs. OpenCL: 6.77331e-06
CPU vs. OpenCL: 8.72863e-07

All differences are within tolerance.
```

B1

```
OpenMM Version: 7.4.2
Git Revision: Unknown

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.30707e-06
Reference vs. OpenCL: 6.75765e-06
CPU vs. OpenCL: 8.71996e-07

All differences are within tolerance.
```

B2

```
OpenMM Version: 7.4.2
Git Revision: Unknown

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.29194e-06
Reference vs. OpenCL: 6.76978e-06
CPU vs. OpenCL: 8.68442e-07

All differences are within tolerance.
```

B3

```
OpenMM Version: 7.4.2
Git Revision: Unknown

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.30743e-06
Reference vs. OpenCL: 6.76535e-06
CPU vs. OpenCL: 8.63013e-07

All differences are within tolerance.
```

B4

```
(openmm_ocl_system) Peter-Eastmans-Computer:tests_osx peastman$ export PYOPENCL_CTX='0'
(openmm_ocl_system) Peter-Eastmans-Computer:tests_osx peastman$ python demo.py

OpenMM Version: 7.4.2
Git Revision: Unknown

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.30389e-06
Reference vs. OpenCL: 6.76075e-06
CPU vs. OpenCL: 8.7116e-07

All differences are within tolerance.
[0. 0. 0. ... 0. 0. 0.]
0.0
(openmm_ocl_system) Peter-Eastmans-Computer:tests_osx peastman$ export PYOPENCL_CTX='1'
(openmm_ocl_system) Peter-Eastmans-Computer:tests_osx peastman$ python demo.py

OpenMM Version: 7.4.2
Git Revision: Unknown

There are 3 Platforms available:

1 Reference - Successfully computed forces
2 CPU - Successfully computed forces
3 OpenCL - Successfully computed forces

Median difference in forces between platforms:

Reference vs. CPU: 6.30183e-06
Reference vs. OpenCL: 6.76154e-06
CPU vs. OpenCL: 8.74087e-07

All differences are within tolerance.
Choose device(s):
[0] <pyopencl.Device 'Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz' on 'Apple' at 0x7fdd6e600e50>
[1] <pyopencl.Device 'Iris Pro' on 'Apple' at 0x7fdd6e644ab0>
[2] <pyopencl.Device 'AMD Radeon R9 M370X Compute Engine' on 'Apple' at 0x7fdd6e61c110>
Choice, comma-separated [0]:2
Set the environment variable PYOPENCL_CTX='1:2' to avoid being asked again.
[0. 0. 0. ... 0. 0. 0.]
0.0
```

Notice that just before the end it paused and asked me to choose a device.  I selected the AMD GPU.

**Comment by jaimergp** [comment]
Sounds good, thanks for the reports!

**Pull request closed without merging**
